FROM tiangolo/uwsgi-nginx-flask:python3.6
ADD requirements.txt /app/requirements.txt
RUN pip install -U pip setuptools
RUN pip install -r /app/requirements.txt

CMD ["sh", "-c", "printf 'created latest worker image'"]